# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./
COPY yarn.lock ./

# Install Dependencies
RUN yarn install

# Copy rest of the code to container
COPY . .

EXPOSE 4200

# Run the Angular app
CMD ["yarn", "run", "start-on-docker"]
