version: "3"
services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    container_name: chai-frontend
    env_file:
      - ./env/.env.dev
    networks:
      -  chai-net
    volumes:
      -  ./frontend/src:/usr/app/src
      -  ./frontend/public:/usr/app/public
    depends_on:
      - nodejs
    stdin_open: true
    tty: true

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    container_name: chai-backend
    env_file:
      - ./env/.env.dev
    networks:
      - chai-net
    volumes:
      - ./backend/src:/usr/app/src
      - ./backend/nodemon.json:/usr/app/nodemon.json
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - chai-net
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - chai-net

networks:
  chai-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local

  cache:
    driver: local