version: "3"
services:

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    container_name: chai-frontend
    networks:
      -  chai-net
    volumes:
      -  ./frontend/src:/usr/app/src
      -  ./frontend/public:/usr/app/public
    depends_on:
      - nodejs
    stdin_open: true
    tty: true

  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    container_name: chai-backend
    networks:
      - chai-net
    volumes:
      - ./backend/src:/usr/app/src
      - ./backend/nodemon.json:/usr/app/nodemon.json
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - chai-net
    volumes:
      - mongo-data:/data/db

  redis-dev:
    image: redis
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  chai-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local

  cache:
    driver: local