# Pull the Node image from Docker Hub
FROM node:bullseye-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying json and lock files
COPY package*.json ./
COPY yarn.lock ./

# Install Dependencies
RUN yarn install
RUN npm install --legacy-peer-deps

# Copy rest of the code to container
COPY . .

EXPOSE 5000

# Run the API on Nodemon
CMD ["yarn", "run", "dev"]